In [1]:
function change_order(order_in::Matrix{Int64})
    m, n = size(order_in)
    print((m,n))
#    order_out = zeros(n)
    order_out = Matrix{Int64}(undef,1,n)
    for i = 1:n
        order_out[order_in[i]] = i
    end
    order_out
end

change_order (generic function with 1 method)

In [2]:
function change_order(order_in::Vector{Int64})
#    m, n = size(order_in)
    n = size(order_in, 1)
    print(n)
#    order_out = zeros(n)
    order_out = Vector{Int64}(undef,n)
    for i = 1:n
        order_out[order_in[i]] = i
    end
    order_out
end

change_order (generic function with 2 methods)

In [3]:
#order_in = Vector{Int}(4)

In [4]:
order_in = [ 1 2 3 4 ]  # 1x4 Matrix{Int64}

1×4 Matrix{Int64}:
 1  2  3  4

In [5]:
#order_in = [1, 2, 3, 4]  # 4-element Vector{Int64}

In [6]:
#order_in = Vector{Int}(undef, 4)

In [7]:
for i = 1:4
    order_in[i] = 5-i
end

In [8]:
print(order_in)

[4 3 2 1]

In [9]:
order_out = change_order(order_in)

(1, 4)

1×4 Matrix{Int64}:
 4  3  2  1