In [1]:
function translate_matrix(c, s)
    c2 = c^2
    cs = c*s
    s2 = s^2
    T = [ c2  cs -c2 -cs;
          cs  s2 -cs -s2;
         -c2 -cs  c2  cs;
         -cs -s2  cs  s2]
end

translate_matrix (generic function with 1 method)

In [2]:
function element_stiffness_matrix(E, A, L, c, s)
    coef = E*A/L
    T = translate_matrix(c, s)
    K = coef * T
end

element_stiffness_matrix (generic function with 1 method)

In [15]:
function assemble_to_global_stiffness_matrix(K_global::Matrix{Float64}, K_element::Matrix{Float64}, dof_table::Vector{Int64})
    n = size(dof_table)
    for j = 1:n
        for i = 1:n
            K_global[dof_table[i], dof_table[j]] = K_global[dof_table[i], dof_table[j]] + K_element[i, j]
        end
    end
    K_global
end

assemble_to_global_stiffness_matrix (generic function with 4 methods)

In [4]:
E = 1; A = 1; L = 1; c = 1; s = 0

0

In [5]:
K_element = element_stiffness_matrix(E, A, L, c, s)

4×4 Matrix{Float64}:
  1.0  0.0  -1.0  0.0
  0.0  0.0   0.0  0.0
 -1.0  0.0   1.0  0.0
  0.0  0.0   0.0  0.0

In [6]:
K_global = zeros(Float64, 4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [7]:
dof_table = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [19]:
K_global = assemble_to_global_stiffness_matrix(K_global, K_element, dof_table)

LoadError: MethodError: no method matching (::Colon)(::Int64, ::Tuple{Int64})

Closest candidates are:
  (::Colon)(::T, ::Any, ::T) where T<:Real
   @ Base range.jl:50
  (::Colon)(::A, ::Any, ::C) where {A<:Real, C<:Real}
   @ Base range.jl:10
  (::Colon)(::T, ::Any, ::T) where T
   @ Base range.jl:49
  ...
